services:
  db:
    image: mysql:8.0
    container_name: sisorg-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sisorg
      MYSQL_USER: sisorg
      MYSQL_PASSWORD: sisorg
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -psisorg || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: ./Sisorg.Api
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "server=db;port=3306;database=sisorg;user=sisorg;password=sisorg;TreatTinyAsBoolean=false"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5196:8080"

  web:
    build:
      context: ./sisorg-front
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:5196"
    ports:
      - "5173:80"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:5196